on: push
name: Test
jobs:
  tox:
    name: Tox
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: pip install tox-conda
    - run: git clone --depth 1 https://github.com/circulosmeos/gdown.pl
    - run: ./gdown.pl/gdown.pl $GAUSSIANURL "g16.tgz">/dev/null 2>&1
      env:
        GAUSSIANURL: ${{ secrets.GAUSSIANURL }}
    - run: tar -xzvf g16.tgz
    - run: tox
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        g16root: /home/runner/work/gaussianrunner/gaussianrunner
        PATH: /home/runner/work/gaussianrunner/gaussianrunner/g16:/home/runner/work/gaussianrunner/gaussianrunner/g16/bsd:$PATH
