on: push
name: Test
jobs:
  tox:
    name: Tox
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: pip install tox
    - run: git clone --depth 1 https://github.com/circulosmeos/gdown.pl
      working-directory: /home/runner/work
    - run: ./gdown.pl/gdown.pl $GAUSSIANURL "g16.tgz">/dev/null 2>&1
      env:
        GAUSSIANURL: ${{ secrets.GAUSSIANURL }}
      working-directory: /home/runner/work
    - run: tar -xzvf g16.tgz
      working-directory: /home/runner/work
    - run: tox
      env:
        g16root: /home/runner/work
